/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) lat_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};

/* lat_expl_vde_forw:(i0[6],i1[6x6],i2[6],i3,i4[])->(o0[6],o1[6x6],o2[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=arg[0]? arg[0][4] : 0;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=(a00*a02);
  a04=arg[0]? arg[0][5] : 0;
  a05=sin(a01);
  a06=(a04*a05);
  a07=arg[0]? arg[0][3] : 0;
  a08=(a00*a07);
  a09=(a06*a08);
  a03=(a03-a09);
  if (res[0]!=0) res[0][0]=a03;
  a03=sin(a01);
  a09=(a00*a03);
  a10=cos(a01);
  a11=(a04*a10);
  a12=(a00*a07);
  a13=(a11*a12);
  a09=(a09+a13);
  if (res[0]!=0) res[0][1]=a09;
  a09=(a00*a07);
  if (res[0]!=0) res[0][2]=a09;
  a09=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][3]=a09;
  a09=0.;
  if (res[0]!=0) res[0][4]=a09;
  if (res[0]!=0) res[0][5]=a09;
  a13=arg[1]? arg[1][4] : 0;
  a14=(a02*a13);
  a15=sin(a01);
  a16=arg[1]? arg[1][2] : 0;
  a17=(a15*a16);
  a17=(a00*a17);
  a14=(a14-a17);
  a17=arg[1]? arg[1][5] : 0;
  a18=(a05*a17);
  a19=cos(a01);
  a20=(a19*a16);
  a20=(a04*a20);
  a18=(a18+a20);
  a18=(a08*a18);
  a20=(a07*a13);
  a21=arg[1]? arg[1][3] : 0;
  a22=(a00*a21);
  a20=(a20+a22);
  a20=(a06*a20);
  a18=(a18+a20);
  a14=(a14-a18);
  if (res[1]!=0) res[1][0]=a14;
  a14=(a03*a13);
  a18=cos(a01);
  a20=(a18*a16);
  a20=(a00*a20);
  a14=(a14+a20);
  a17=(a10*a17);
  a20=sin(a01);
  a16=(a20*a16);
  a16=(a04*a16);
  a17=(a17-a16);
  a17=(a12*a17);
  a16=(a07*a13);
  a22=(a00*a21);
  a16=(a16+a22);
  a16=(a11*a16);
  a17=(a17+a16);
  a14=(a14+a17);
  if (res[1]!=0) res[1][1]=a14;
  a13=(a07*a13);
  a21=(a00*a21);
  a13=(a13+a21);
  if (res[1]!=0) res[1][2]=a13;
  if (res[1]!=0) res[1][3]=a09;
  if (res[1]!=0) res[1][4]=a09;
  if (res[1]!=0) res[1][5]=a09;
  a13=arg[1]? arg[1][10] : 0;
  a21=(a02*a13);
  a14=arg[1]? arg[1][8] : 0;
  a17=(a15*a14);
  a17=(a00*a17);
  a21=(a21-a17);
  a17=arg[1]? arg[1][11] : 0;
  a16=(a05*a17);
  a22=(a19*a14);
  a22=(a04*a22);
  a16=(a16+a22);
  a16=(a08*a16);
  a22=(a07*a13);
  a23=arg[1]? arg[1][9] : 0;
  a24=(a00*a23);
  a22=(a22+a24);
  a22=(a06*a22);
  a16=(a16+a22);
  a21=(a21-a16);
  if (res[1]!=0) res[1][6]=a21;
  a21=(a03*a13);
  a16=(a18*a14);
  a16=(a00*a16);
  a21=(a21+a16);
  a17=(a10*a17);
  a14=(a20*a14);
  a14=(a04*a14);
  a17=(a17-a14);
  a17=(a12*a17);
  a14=(a07*a13);
  a16=(a00*a23);
  a14=(a14+a16);
  a14=(a11*a14);
  a17=(a17+a14);
  a21=(a21+a17);
  if (res[1]!=0) res[1][7]=a21;
  a13=(a07*a13);
  a23=(a00*a23);
  a13=(a13+a23);
  if (res[1]!=0) res[1][8]=a13;
  if (res[1]!=0) res[1][9]=a09;
  if (res[1]!=0) res[1][10]=a09;
  if (res[1]!=0) res[1][11]=a09;
  a13=arg[1]? arg[1][16] : 0;
  a23=(a02*a13);
  a21=arg[1]? arg[1][14] : 0;
  a17=(a15*a21);
  a17=(a00*a17);
  a23=(a23-a17);
  a17=arg[1]? arg[1][17] : 0;
  a14=(a05*a17);
  a16=(a19*a21);
  a16=(a04*a16);
  a14=(a14+a16);
  a14=(a08*a14);
  a16=(a07*a13);
  a22=arg[1]? arg[1][15] : 0;
  a24=(a00*a22);
  a16=(a16+a24);
  a16=(a06*a16);
  a14=(a14+a16);
  a23=(a23-a14);
  if (res[1]!=0) res[1][12]=a23;
  a23=(a03*a13);
  a14=(a18*a21);
  a14=(a00*a14);
  a23=(a23+a14);
  a17=(a10*a17);
  a21=(a20*a21);
  a21=(a04*a21);
  a17=(a17-a21);
  a17=(a12*a17);
  a21=(a07*a13);
  a14=(a00*a22);
  a21=(a21+a14);
  a21=(a11*a21);
  a17=(a17+a21);
  a23=(a23+a17);
  if (res[1]!=0) res[1][13]=a23;
  a13=(a07*a13);
  a22=(a00*a22);
  a13=(a13+a22);
  if (res[1]!=0) res[1][14]=a13;
  if (res[1]!=0) res[1][15]=a09;
  if (res[1]!=0) res[1][16]=a09;
  if (res[1]!=0) res[1][17]=a09;
  a13=arg[1]? arg[1][22] : 0;
  a22=(a02*a13);
  a23=arg[1]? arg[1][20] : 0;
  a17=(a15*a23);
  a17=(a00*a17);
  a22=(a22-a17);
  a17=arg[1]? arg[1][23] : 0;
  a21=(a05*a17);
  a14=(a19*a23);
  a14=(a04*a14);
  a21=(a21+a14);
  a21=(a08*a21);
  a14=(a07*a13);
  a16=arg[1]? arg[1][21] : 0;
  a24=(a00*a16);
  a14=(a14+a24);
  a14=(a06*a14);
  a21=(a21+a14);
  a22=(a22-a21);
  if (res[1]!=0) res[1][18]=a22;
  a22=(a03*a13);
  a21=(a18*a23);
  a21=(a00*a21);
  a22=(a22+a21);
  a17=(a10*a17);
  a23=(a20*a23);
  a23=(a04*a23);
  a17=(a17-a23);
  a17=(a12*a17);
  a23=(a07*a13);
  a21=(a00*a16);
  a23=(a23+a21);
  a23=(a11*a23);
  a17=(a17+a23);
  a22=(a22+a17);
  if (res[1]!=0) res[1][19]=a22;
  a13=(a07*a13);
  a16=(a00*a16);
  a13=(a13+a16);
  if (res[1]!=0) res[1][20]=a13;
  if (res[1]!=0) res[1][21]=a09;
  if (res[1]!=0) res[1][22]=a09;
  if (res[1]!=0) res[1][23]=a09;
  a13=arg[1]? arg[1][28] : 0;
  a16=(a02*a13);
  a22=arg[1]? arg[1][26] : 0;
  a17=(a15*a22);
  a17=(a00*a17);
  a16=(a16-a17);
  a17=arg[1]? arg[1][29] : 0;
  a23=(a05*a17);
  a21=(a19*a22);
  a21=(a04*a21);
  a23=(a23+a21);
  a23=(a08*a23);
  a21=(a07*a13);
  a14=arg[1]? arg[1][27] : 0;
  a24=(a00*a14);
  a21=(a21+a24);
  a21=(a06*a21);
  a23=(a23+a21);
  a16=(a16-a23);
  if (res[1]!=0) res[1][24]=a16;
  a16=(a03*a13);
  a23=(a18*a22);
  a23=(a00*a23);
  a16=(a16+a23);
  a17=(a10*a17);
  a22=(a20*a22);
  a22=(a04*a22);
  a17=(a17-a22);
  a17=(a12*a17);
  a22=(a07*a13);
  a23=(a00*a14);
  a22=(a22+a23);
  a22=(a11*a22);
  a17=(a17+a22);
  a16=(a16+a17);
  if (res[1]!=0) res[1][25]=a16;
  a13=(a07*a13);
  a14=(a00*a14);
  a13=(a13+a14);
  if (res[1]!=0) res[1][26]=a13;
  if (res[1]!=0) res[1][27]=a09;
  if (res[1]!=0) res[1][28]=a09;
  if (res[1]!=0) res[1][29]=a09;
  a13=arg[1]? arg[1][34] : 0;
  a14=(a02*a13);
  a16=arg[1]? arg[1][32] : 0;
  a15=(a15*a16);
  a15=(a00*a15);
  a14=(a14-a15);
  a15=arg[1]? arg[1][35] : 0;
  a17=(a05*a15);
  a19=(a19*a16);
  a19=(a04*a19);
  a17=(a17+a19);
  a17=(a08*a17);
  a19=(a07*a13);
  a22=arg[1]? arg[1][33] : 0;
  a23=(a00*a22);
  a19=(a19+a23);
  a19=(a06*a19);
  a17=(a17+a19);
  a14=(a14-a17);
  if (res[1]!=0) res[1][30]=a14;
  a14=(a03*a13);
  a18=(a18*a16);
  a18=(a00*a18);
  a14=(a14+a18);
  a15=(a10*a15);
  a20=(a20*a16);
  a20=(a04*a20);
  a15=(a15-a20);
  a15=(a12*a15);
  a20=(a07*a13);
  a16=(a00*a22);
  a20=(a20+a16);
  a20=(a11*a20);
  a15=(a15+a20);
  a14=(a14+a15);
  if (res[1]!=0) res[1][31]=a14;
  a13=(a07*a13);
  a22=(a00*a22);
  a13=(a13+a22);
  if (res[1]!=0) res[1][32]=a13;
  if (res[1]!=0) res[1][33]=a09;
  if (res[1]!=0) res[1][34]=a09;
  if (res[1]!=0) res[1][35]=a09;
  a13=arg[2]? arg[2][4] : 0;
  a02=(a02*a13);
  a22=sin(a01);
  a14=arg[2]? arg[2][2] : 0;
  a22=(a22*a14);
  a22=(a00*a22);
  a02=(a02-a22);
  a22=arg[2]? arg[2][5] : 0;
  a05=(a05*a22);
  a15=cos(a01);
  a15=(a15*a14);
  a15=(a04*a15);
  a05=(a05+a15);
  a08=(a08*a05);
  a05=(a07*a13);
  a15=arg[2]? arg[2][3] : 0;
  a20=(a00*a15);
  a05=(a05+a20);
  a06=(a06*a05);
  a08=(a08+a06);
  a02=(a02-a08);
  if (res[2]!=0) res[2][0]=a02;
  a03=(a03*a13);
  a02=cos(a01);
  a02=(a02*a14);
  a02=(a00*a02);
  a03=(a03+a02);
  a10=(a10*a22);
  a01=sin(a01);
  a01=(a01*a14);
  a04=(a04*a01);
  a10=(a10-a04);
  a12=(a12*a10);
  a10=(a07*a13);
  a04=(a00*a15);
  a10=(a10+a04);
  a11=(a11*a10);
  a12=(a12+a11);
  a03=(a03+a12);
  if (res[2]!=0) res[2][1]=a03;
  a07=(a07*a13);
  a00=(a00*a15);
  a07=(a07+a00);
  if (res[2]!=0) res[2][2]=a07;
  a07=1.;
  if (res[2]!=0) res[2][3]=a07;
  if (res[2]!=0) res[2][4]=a09;
  if (res[2]!=0) res[2][5]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void lat_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int lat_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real lat_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* lat_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* lat_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int lat_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
